10 enforce mint cap
GoodDollar/GoodProtocol pull request #35
Opened 2021-04-21 12:32 UTC by sirpy

# Description
Add a GoodCap contract which will be the only Minter besides the Controller
- it holds a MINTER_ROLE to allow contracts to use it to mint
- it implements GlobaConstraint so it can also enforce cap on the Controller mintTokens method

About #14

2021-04-21 13:38 UTC, aliberkhsl requested changes

2021-04-21 13:38 UTC, aliberkhsl commented on contracts/reserve/GoodReserveCDai.sol
> +	// 	uint256 priceInCDai = getMarketMaker().currentPrice(ERC20(cDaiAddress));
Why did you comment out this one?

2021-04-26 11:35 UTC, sirpy commented
@aliberkhsl this is ready for review

2021-04-26 12:30 UTC, aliberkhsl approved these changes

2021-04-26 14:40 UTC, merged